export const PRODUCT_PATTERN = {
  TEST: 'TEST',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  FIND_ALL_PRODUCT: 'FIND_ALL_PRODUCT',
  OTHER_RANDOM_PRODUCT: 'OTHER_RANDOM_PRODUCT',
  FIND_5_PRODUCTS_IN_THE_SAME_CATEGORY: 'FIND_5_PRODUCTS_IN_THE_SAME_CATEGORY',
  FIND_ALL_PRODUCT_OF_SHOP: 'FIND_ALL_PRODUCT_OF_SHOP',
  FIND_ONE_PRODUCT: 'FIND_ONE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
  BACK_TO_SELL: 'BACK_TO_SELL',
};

export const BRAND_PATTERN = {
  CREATE_BRAND: 'CREATE_BRAND',
  UPDATE_BRAND: 'UPDATE_BRAND',
  GET_ALL_BRANDS: 'GET_ALL_BRANDS',
  GET_BRAND: 'GET_BRAND',
  GET_BRAND_BY_NAME: 'GET_BRAND_BY_NAME',
};

export const CATEGORY_PATTERN = {
  CREATE_CATEGORY: 'CREATE_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  GET_ALL_CATEGORIES: 'GET_ALL_CATEGORIES',
  GET_CATEGORY: 'GET_CATEGORY',
};

export const SHOP_PATTERN = {
  CREATE_SHOP: 'CREATE_SHOP',
  UPDATE_SHOP: 'UPDATE_SHOP',
  GET_ALL_SHOPS: 'GET_ALL_SHOPS',
  GET_SHOP: 'GET_SHOP',
  GET_SHOP_BY_NAME: 'GET_SHOP_BY_NAME',
  GET_SHOPS_NOT_APPROVED: 'GET_SHOPS_NOT_APPROVED',
  APPROVE_SHOP: 'APPROVE_SHOP',
};

export const SEARCHING_PATTERN = {
  SEARCH_PRODUCTS_USING_KNN: 'SEARCH_PRODUCTS_USING_KNN',
  SEARCH_PRODUCTS: 'SEARCH_PRODUCTS',
};

export const ORDER_PATTERN = {
  CREATE_ORDER: 'CREATE_ORDER',
  CANCEL_ORDER: 'CANCEL_ORDER',
  UPDATE_ORDER_STATUS: 'UPDATE_ORDER_STATUS',
  GET_ALL_ORDERS: 'GET_ALL_ORDERS',
  GET_ALL_ORDERS_PREPARED_FOR_SHOP: 'GET_ALL_ORDERS_PREPARED_FOR_SHOP',
  GET_ALL_ORDERS_FOR_SHOP: 'GET_ALL_ORDERS_FOR_SHOP',
  GET_ALL_ORDERS_FOR_ADMIN: 'GET_ALL_ORDERS_FOR_ADMIN',
  GET_ORDER: 'GET_ORDER',
  GET_ALL_PAYMENT_METHOD: 'GET_ALL_PAYMENT_METHOD',
  GET_ALL_SHIPPING_METHOD: 'GET_ALL_SHIPPING_METHOD',
  GET_PAYMENT_METHOD: 'GET_PAYMENT_METHOD',
  GET_SHIPPING_METHOD: 'GET_SHIPPING_METHOD',
  PAY_ORDER: 'PAY_ORDER',
};

export const CART_PATTERN = {
  ADD_TO_CART: 'ADD_TO_CART',
  CHANGE_QUANTITY: 'CHANGE_QUANTITY',
  UPDATE_CART: 'UPDATE_CART',
  DELETE_FROM_CART: 'DELETE_FROM_CART',
  CREATE_CART: 'CREATE_CART',
  GET_CART: 'GET_CART',
};

export const RATING_PATTERN = {
  GET_PRODUCT_RATING: 'GET_PRODUCT_RATING',
  CREATE_RATING: 'CREATE_RATING',
  UPDATE_RATING: 'UPDATE_RATING',
  DELETE_RATING: 'DELETE_RATING',
  GET_ALL_RATING_OF_PRODUCT: 'GET_ALL_RATING_OF_PRODUCT',
  GET_ALL_RATING_OF_USER: 'GET_ALL_RATING_OF_USER',
  GET_RATING: 'GET_RATING',
};
