export const PRODUCT_PATTERN = {
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  FIND_ALL_PRODUCT: 'FIND_ALL_PRODUCT',
  FIND_ONE_PRODUCT: 'FIND_ONE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
};
