services:
  postgres:
    image: postgres
    container_name: ending_project
    restart: 'always'
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./docker/postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.9.20-management-alpine
    container_name: rabbitmq
    ports:
      - ${RABBITMQ_MAIN_PORT}:5672
      - ${RABBITMQ_SUB_PORT}:15672
    volumes:
      - ./docker/rabbitmq_data:/var/lib/rabbitmq

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    container_name: lms_elastic_search
    restart: always
    volumes:
      - ./docker/elastic_data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
      # turn on or off
      # xpack.security.enabled: false

    env_file:
      - .env
    ports:
      - ${ELASTIC_PORT}:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:${ES_VERSION}
    container_name: lms_kibana
    restart: always
    env_file:
      - .env
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - ELASTICSEARCH_URL=https://lms_elastic_search:9200
    depends_on:
      - elasticsearch
    networks:
      - elastic

volumes:
  postgres_data:
  rabbitmq_data:
  elastic_data:

networks:
  elastic: