apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: ecom
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000 # Backend is running on port 8081
      targetPort: 3000 # Match container's port
      nodePort: 30003
  type: NodePort # Expose backend via NodePort
  # type: ClusterIP # Expose backend via NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: ecom
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # Match container's port
      nodePort: 30080
  type: NodePort # Expose backend via NodePort
  # type: ClusterIP # Expose backend via NodePort
