@startuml OrderStatistics

hide footbox
autonumber
participant Shop as shop
control "StatisticController" as statisticController
entity "Shop" as shopEntity

shop -> statisticController: Chọn chức năng thống kê
statisticController -> shopEntity: Lấy thông tin đơn hàng (đã thanh toán, chưa thanh toán, hủy, không thành công)
shopEntity --> statisticController: Trả về thông tin đơn hàng của shop
statisticController --> shop: Hiển thị thông tin thống kê (số tiền đã thanh toán, chưa thanh toán, hủy, không thành công)

shop -> statisticController: Gửi yêu cầu thống kê theo filter (Tuần, Tháng, Năm)
statisticController -> shopEntity: Lấy thông tin thống kê theo filter
shopEntity --> statisticController: Trả về thông tin thống kê theo tuần, tháng, năm
statisticController --> shop: Hiển thị thông tin thống kê theo filter (tuần, tháng, năm)

@enduml
