apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: ecom
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgresql
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /data/pgdata
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc # Reference to the persistent volume claim for storage
