apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: ecom
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ebs-sc
